#!/bin/bash
# Usage: ./clone_custom_voice.sh <input_audio_path> [optional_text_to_speak]

if [ -z "$1" ]; then
    echo "Usage: $0 <input_audio_path> [optional_text_to_speak]"
    exit 1
fi

INPUT_AUDIO="$1"
CUSTOM_TEXT="$2"

# Paths (Adjust if running outside the standard environment)
export PYTHONPATH=/home/ubuntu/regional_voice_engine/f5_tts_repo/src
VENV_PYTHON="/home/ubuntu/regional_voice_engine/venv/bin/python3"
USER_DIR="/home/ubuntu/regional_voice_engine/user_samples"
mkdir -p "$USER_DIR"

FILENAME=$(basename -- "$INPUT_AUDIO")
FILENAME="${FILENAME%.*}"
WAV_24K="$USER_DIR/${FILENAME}_24k.wav"

echo "🔄 Converting '$INPUT_AUDIO' to 24kHz WAV..."
ffmpeg -i "$INPUT_AUDIO" -ac 1 -ar 24000 "$WAV_24K" -y

echo "📝 Transcribing voice sample using Whisper..."
$VENV_PYTHON -c "
import whisper
import sys
try:
    model = whisper.load_model('base')
    result = model.transcribe('$WAV_24K')
    print(result['text'].strip())
except Exception as e:
    print(f'Error: {e}', file=sys.stderr)
" > "$USER_DIR/${FILENAME}_transcription.txt"

REF_TEXT=$(cat "$USER_DIR/${FILENAME}_transcription.txt")
echo "✅ Transcription: '$REF_TEXT'"

# Default text if not provided
if [ -z "$CUSTOM_TEXT" ]; then
    GEN_TEXT="This is a cloned voice sample generated by the VideoAvatar UK Regional Engine. The voice you are hearing is a digital replica created from a short reference audio."
else
    GEN_TEXT="$CUSTOM_TEXT"
fi

OUTPUT_DIR="/home/ubuntu/regional_voice_engine/cloned_voices/$(date +%Y%m%d_%H%M)_${FILENAME}"
mkdir -p "$OUTPUT_DIR"

echo "🚀 Generating cloned voice sample..."
cd /home/ubuntu/regional_voice_engine/f5_tts_repo/src/f5_tts/infer/

$VENV_PYTHON infer_cli.py \
    --model_cfg /home/ubuntu/regional_voice_engine/f5_tts_repo/src/f5_tts/configs/train_uk_model.yaml \
    --ckpt_file /home/ubuntu/regional_voice_engine/f5_tts_repo/ckpts/uk_regional/model_last.pt \
    --ref_audio "$WAV_24K" \
    --ref_text "$REF_TEXT" \
    --gen_text "$GEN_TEXT" \
    --output_dir "$OUTPUT_DIR" \
    --output_file "cloned_sample.wav" \
    --device cuda \
    --speed 1.0 \
    --cfg_strength 2.0 \
    --remove_silence

echo "✨ Voice clone ready at: $OUTPUT_DIR/cloned_sample.wav"
